apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistant-volume-claim
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
